# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [1]:
import pandas as pd
import numpy as np

#### Import data set.

Import data set `Pokemon` from [kaggle](https://www.kaggle.com/abcsds/pokemon/) . Read the data into a dataframe called `pokemon`.

In [2]:
df=pd.read_csv(r'C:\Users\Lorenzo\Desktop\IRONHACK REPOSITORIES\2.3-lab_df_calculation_and_transformation\your-code\Pokemon.csv')

#### Print first 10 rows of `pokemon`.

In [3]:
df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [18]:
df[['Type 1', 'Type 2']].head()

  Type 1  Type 2
0  Grass  Poison
1  Grass  Poison
2  Grass  Poison
3  Grass  Poison
4   Fire     NaN

In [19]:
df.columns = (['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp.Atk', 'Sp.Def', 'Speed', 'Generation', 'Legendary'])
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp.Atk', 'Sp.Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [21]:
def limpiar_pokemon(nombre):
    
    if 'Mega ' in nombre:
        
        nombre = nombre.split('Mega ')[0]
        
        return 'Mega ' + nombre
    
    return nombre

In [22]:
df.Name=df.Name.apply(limpiar_pokemon)
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [23]:
df['AD_Ratio']= df.Attack/df.Defense
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,Speed,Generation,Legendary,AD_Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302

#### Identify the pokemon with the highest `A/D Ratio`.

In [24]:
df.AD_Ratio.idxmax() #.idxmax() me da el indice del valor máximo de la columna AD_Ratio de el DataFrame df.

429

In [25]:
df.loc[429] #.loc[] de un indice me da toda la informacion de la fila que corresponde a dicho indice.

#                            386
Name          DeoxysAttack Forme
Type 1                   Psychic
Type 2                       NaN
Total                        600
HP                            50
Attack                       180
Defense                       20
Sp.Atk                       180
Sp.Def                        20
Speed                        150
Generation                     3
Legendary                   True
AD_Ratio                     9.0
Name: 429, dtype: object

#### Identify the pokemon with the lowest A/D Ratio.

In [26]:
df.AD_Ratio.idxmin()

230

In [27]:
df.loc[230]

#                  213
Name           Shuckle
Type 1             Bug
Type 2            Rock
Total              505
HP                  20
Attack              10
Defense            230
Sp.Atk              10
Sp.Def             230
Speed                5
Generation           2
Legendary        False
AD_Ratio      0.043478
Name: 230, dtype: object

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [30]:
df['Combo_Type']= df['Type 1'].fillna('')  + df['Type 2'].fillna('')

In [31]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,Speed,Generation,Legendary,AD_Ratio,Combo_Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,GrassPoison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,GrassPoison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,GrassPoison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,GrassPoison
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302,Fire

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [33]:
df.AD_Ratio.sort_values(ascending=False)

429    9.000000
347    4.500000
19     3.750000
453    3.125000
348    3.000000
         ...
616    0.285714
103    0.281250
484    0.279070
139    0.181818
230    0.043478
Name: AD_Ratio, Length: 800, dtype: float64

In [32]:
print(df.loc[429])
print(df.loc[347])
print(df.loc[19])
print(df.loc[453])
print(df.loc[348])

#                            386
Name          DeoxysAttack Forme
Type 1                   Psychic
Type 2                       NaN
Total                        600
HP                            50
Attack                       180
Defense                       20
Sp.Atk                       180
Sp.Def                        20
Speed                        150
Generation                     3
Legendary                   True
AD_Ratio                     9.0
Combo_Type               Psychic
Name: 429, dtype: object
#                   318
Name           Carvanha
Type 1            Water
Type 2             Dark
Total               305
HP                   45
Attack               90
Defense              20
Sp.Atk               65
Sp.Def               20
Speed                65
Generation            3
Legendary         False
AD_Ratio            4.5
Combo_Type    WaterDark
Name: 347, dtype: object
#                        15
Name          Mega Beedrill
Type 1                  Bug
Type 2               Poison
Total                   495
HP                       65
Attack                  150
Defense                  40
Sp.Atk                   15
Sp.Def                   80
Speed                   145
Generation                1
Legendary             False
AD_Ratio               3.75
Combo_Type        BugPoison
Name: 19, dtype: object
#                  408
Name          Cranidos
Type 1            Rock
Type 2             NaN
Total              350
HP                  67
Attack             125
Defense             40
Sp.Atk              30
Sp.Def              30
Speed               58
Generation           4
Legendary        False
AD_Ratio         3.125
Combo_Type        Rock
Name: 453, dtype: object
#                   319
Name           Sharpedo
Type 1            Water
Type 2             Dark
Total               460
HP                   70
Attack              120
Defense              40
Sp.Atk               95
Sp.Def               40
Speed                95
Generation            3
Legendary         False
AD_Ratio            3.0
Combo_Type    WaterDark
Name: 348, dtype: object

In [34]:
top5 = df.nlargest(5, 'AD_Ratio') 
top5

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,Speed,Generation,Legendary,AD_Ratio,Combo_Type
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000,Psychic
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,WaterDark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,BugPoison
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125,Rock
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,WaterDark

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [35]:
top5.groupby(['Combo_Type']).sum()

,#,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,Speed,Generation,Legendary,AD_Ratio
Combo_Type,,,,,,,,,,,
BugPoison,15,495,65,150,40,15,80,145,1,0,3.750
Psychic,386,600,50,180,20,180,20,150,3,1,9.000
Rock,408,350,67,125,40,30,30,58,4,0,3.125
WaterDark,637,765,115,210,60,160,60,160,6,0,7.500

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [39]:
df.groupby(['Combo_Type']).mean().head(30)

,#,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,Speed,Generation,Legendary,AD_Ratio
Combo_Type,,,,,,,,,,,
Bug,361.352941,289.705882,53.058824,50.352941,55.411765,39.294118,43.647059,47.941176,3.470588,0.000000,0.940179
BugElectric,595.500000,395.500000,60.000000,62.000000,55.000000,77.000000,55.000000,86.500000,5.000000,0.000000,1.111667
BugFighting,214.000000,550.000000,80.000000,155.000000,95.000000,40.000000,100.000000,80.000000,2.000000,0.000000,1.637681
BugFire,636.500000,455.000000,70.000000,72.500000,60.000000,92.500000,80.000000,80.000000,5.000000,0.000000,1.234266
BugFlying,286.285714,419.500000,63.000000,70.142857,61.571429,72.857143,69.071429,82.857143,2.857143,0.000000,1.146274
BugGhost,292.000000,236.000000,1.000000,90.000000,45.000000,30.000000,30.000000,40.000000,3.000000,0.000000,2.000000
BugGrass,354.833333,384.000000,55.000000,73.833333,76.666667,57.333333,76.666667,44.500000,3.500000,0.000000,0.983165
BugGround,351.500000,345.000000,45.500000,62.000000,97.500000,44.500000,57.500000,38.000000,3.500000,0.000000,0.626190
BugPoison,199.166667,347.916667,53.750000,68.333333,58.083333,42.500000,59.333333,65.916667,2.333333,0.000000,1.315989
BugRock,442.666667,435.000000,46.666667,56.666667,146.666667,36.666667,113.333333,35.000000,4.000000,0.000000,0.522728
BugSteel,416.000000,509.714286,67.714286,114.714286,112.428571,68.142857,83.285714,63.428571,3.571429,0.000000,1.037527
BugWater,283.000000,269.000000,40.000000,30.000000,32.000000,50.000000,52.000000,65.000000,3.000000,0.000000,0.937500
Dark,408.900000,436.200000,60.500000,88.800000,61.200000,81.300000,61.700000,82.700000,3.800000,0.100000,1.560107
DarkDragon,634.000000,440.000000,72.000000,85.000000,70.000000,78.333333,70.000000,64.666667,5.000000,0.000000,1.226984
DarkFighting,559.500000,418.000000,57.500000,82.500000,92.500000,40.000000,92.500000,53.000000,5.000000,0.000000,0.927019
DarkFire,228.666667,476.666667,65.000000,80.000000,56.666667,110.000000,73.333333,91.666667,2.000000,0.000000,1.600000
DarkFlying,520.800000,494.000000,93.200000,92.200000,73.800000,84.200000,70.400000,80.200000,4.400000,0.200000,1.431797
DarkGhost,302.000000,430.000000,50.000000,80.000000,100.000000,75.000000,90.000000,35.000000,3.000000,0.000000,0.840000
DarkIce,338.000000,470.000000,62.500000,107.500000,60.000000,40.000000,80.000000,120.000000,3.000000,0.000000,1.786713
DarkPsychic,686.500000,385.000000,69.500000,73.000000,70.500000,52.500000,60.500000,59.000000,6.000000,0.000000,1.032161
DarkSteel,624.500000,415.000000,55.000000,105.000000,85.000000,50.000000,55.000000,65.000000,5.000000,0.000000,1.232143
Dragon,509.727273,413.363636,61.818182,92.181818,67.090909,59.818182,71.636364,60.818182,4.181818,0.000000,1.388624
DragonElectric,644.000000,680.000000,100.000000,150.000000,120.000000,120.000000,100.000000,90.000000,5.000000,1.000000,1.250000
DragonFairy,334.000000,590.000000,75.000000,110.000000,110.000000,110.000000,105.000000,80.000000,3.000000,0.000000,1.000000
DragonFire,643.000000,680.000000,100.000000,120.000000,100.000000,150.000000,120.000000,90.000000,5.000000,1.000000,1.200000
DragonFlying,332.833333,641.666667,94.333333,135.666667,97.500000,121.666667,94.166667,98.333333,2.666667,0.333333,1.409643
DragonGround,499.000000,522.000000,90.000000,112.000000,88.200000,74.200000,75.000000,82.600000,4.400000,0.200000,1.322660
DragonIce,646.000000,686.666667,125.000000,140.000000,93.333333,140.000000,93.333333,95.000000,5.000000,1.000000,1.492593
DragonPsychic,380.500000,650.000000,80.000000,100.000000,97.500000,135.000000,127.500000,110.000000,3.000000,1.000000,1.036806
Electric,303.962963,413.555556,60.000000,69.222222,55.296296,78.148148,66.370370,84.518519,2.888889,0.037037,1.323922